W7D2/music_app/config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands

end

W7D2/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
end

W7D2/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = find_by(email: email)

    return nil if user.nil?

    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    password_object = BCrypt::Password.new(self.password_digest)
    password_object.is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end 
end

W7D2/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :signed_in?, :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def signed_in?
    !!current_user
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

W7D2/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  
  def index
    @bands = Band.all
    # render :index
    render json: @bands
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      # redirect_to band_url(@band)
      render json: @band
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

end

W7D2/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  before_action :require_signed_in!, only: [:destroy]

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      login!(@user)
      redirect_to user_url
    else
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end

end

W7D2/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to #somewhere
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W7D2/music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
      type='hidden'
      name='authenticity_token'
      value='<%= form_authenticity_token %>'
    />".html_safe
  end
end

W7D2/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W7D2/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7D2/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W7D2/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      <form action="<%= session_url %>" method="POST">
      <form action="hidden" name="_method" value="DELETE"></form>
        <%= auth_token %>
        <button>Sign Out</button>
      </form>
    <% else %>

    <% end %>

    <% if flash[:errors] %>
      <%= flash[:errors].join(',') %>
    <% end %>

    <%= yield %>
  </body>
</html>

W7D2/music_app/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  <%= auth_token %>
  <label for="email">Email: </label>
  <input type="text" name="user[email]" id="email" value="<%= @user.email %>">

  <label for="password">Password: </label>
  <input type="password" name="user[password]" id="password">
  <input type="submit" value="Sign Up">
</form>